### ISSUE TITLE
Works on Debian 8, Fails on Debian 9

### ISSUE THREAD

**Issue by ssokol** [dmichael/go-multicast#1]
Trying to use the listen portion of this code on a number of Raspberry Pi systems. It works on systems running Debian 8 (jessie) but fails on systems running Debian 9 (stretch) with the following error:

```
2019/02/14 03:22:52 listen udp 239.255.1.1:49707: setsockopt: no such device
```

I tried assigning a specific interface in the listen function, but that didn't fix the issue. Any guess what's going on?

**Comment by dmichael** [comment]
Thanks for reporting this. Gimme a day or 2 and I’d be happy to
troubleshoot.

Which OS distribution are you using?

**Comment by ssokol** [comment]
The error is on Raspbian 9.4 (the Pi-specific variant of Debian 9.4). The kernel definitely supports multicast, and it appears to be enabled on the interface:

```
root@flightbox-sim(rw):~/mcst# ifconfig eth0|grep -i multi
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
```

I'm building on both the older Debian 8 machine (which works) and on the 9.4 machine using the latest version of go for this platform: ``go version go1.13 linux/arm``

There is a difference in hardware. The older system is a Raspberry Pi 3 B and the newer (failure) system is a 3 B+. I'm not aware of any networking-specific hardware changes between the two models.

**Comment by dmichael** [comment]
Excellent @ssokol. Just so that I am clear: you have Raspbian 8 on the RPi 3B and Raspbian 9 on the RPi 3B+. Have you installed 9 on the RPi 3B (attempting to isolate the issue to the OS or the hardware)?

I have (or can get) both machines here and will experiment as well. I am manically booked until Thursday of this coming week, but will begin testing after.

**Comment by ssokol** [comment]
Correct - works on 8/3B, fails on 9/3B+. I have not tried running the 9 image on the 3B but will do so today.

Any chance this might be an IPv4 / IPv6 thing? The documentation for the ``ListenMulticastUDP()`` function shows as:

```
ListenMulticastUDP acts like ListenPacket for UDP networks but takes a group address on a specific network interface.

The network must be a UDP network name; see func Dial for details.
```

The docs for Dial show:

```
Known networks are "tcp", "tcp4" (IPv4-only), "tcp6" (IPv6-only), "udp", "udp4" (IPv4-only), "udp6" (IPv6-only), "ip", "ip4" (IPv4-only), "ip6" (IPv6-only), "unix", "unixgram" and "unixpacket".
```

I wonder if the call in your code needs to use "udp4" on newer systems? There's a pretty serious push to make all things IPv6-capable, so perhaps they changed the underling stack to require you indicate which version you want.

I'll give that a try tomorrow and see if it makes any difference.

**Comment by dmichael** [comment]
The "udp4" argument seems like a reasonable assumption here since all the underlying code assumes IPv4. If this turns out to be the case, I can refactor these be a little more flexible with regards to IP versions so that while it defaults to v4, the user could specify if needed.

**Comment by ssokol** [comment]
That appears to be the fix. I changed the code as follows and it worked.

```
// Listen binds to the UDP address and port given and writes packets received
// from that address to a buffer which is passed to a hander
func Listen(address string, handler func(*net.UDPAddr, int, []byte)) {
	// Parse the string address
	addr, err := net.ResolveUDPAddr("udp4", address)
	if err != nil {
		log.Fatal(err)
	}

    // TEMP - use only the eth0 interface
    ifc, err := net.InterfaceByName("eth0")
    if err != nil {
        log.Fatal(err)
    }
    
	// Open up a connection
	conn, err := net.ListenMulticastUDP("udp4", ifc, addr)
	if err != nil {
		log.Fatal(err)
	}

	conn.SetReadBuffer(maxDatagramSize)

	// Loop forever reading from the socket
	for {
		buffer := make([]byte, maxDatagramSize)
		numBytes, src, err := conn.ReadFromUDP(buffer)
		if err != nil {
			log.Fatal("ReadFromUDP failed:", err)
		}

		handler(src, numBytes, buffer)
	}
}
```

**Comment by dmichael** [comment]
🍾 Nice one. I'll push a fix now to the main repo.

**Comment by dmichael** [comment]
@ssokol have a look at https://github.com/dmichael/go-multicast/pull/2 and gimme the OK

**Comment by ssokol** [comment]
Pulled. Tested. Looks good to me!
